// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbD7aaadNloA3r-DXrce6rSI5nnFCj78w',
    appId: '1:1059506692920:web:05183179d9763fdc4797cd',
    messagingSenderId: '1059506692920',
    projectId: 'my-shopping-app-133cf',
    authDomain: 'my-shopping-app-133cf.firebaseapp.com',
    storageBucket: 'my-shopping-app-133cf.appspot.com',
    measurementId: 'G-E065RFY377',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLz8BTx52RTLvHssEmiNs8eG2Inj7sbQM',
    appId: '1:1059506692920:android:5314f6d56d2d774a4797cd',
    messagingSenderId: '1059506692920',
    projectId: 'my-shopping-app-133cf',
    storageBucket: 'my-shopping-app-133cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx3Fp9m5Z9x0NXuE14P1MtPzMXdqqu4Hs',
    appId: '1:1059506692920:ios:7b79d7fb29db61c24797cd',
    messagingSenderId: '1059506692920',
    projectId: 'my-shopping-app-133cf',
    storageBucket: 'my-shopping-app-133cf.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx3Fp9m5Z9x0NXuE14P1MtPzMXdqqu4Hs',
    appId: '1:1059506692920:ios:7b79d7fb29db61c24797cd',
    messagingSenderId: '1059506692920',
    projectId: 'my-shopping-app-133cf',
    storageBucket: 'my-shopping-app-133cf.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbD7aaadNloA3r-DXrce6rSI5nnFCj78w',
    appId: '1:1059506692920:web:979392cf70106e4d4797cd',
    messagingSenderId: '1059506692920',
    projectId: 'my-shopping-app-133cf',
    authDomain: 'my-shopping-app-133cf.firebaseapp.com',
    storageBucket: 'my-shopping-app-133cf.appspot.com',
    measurementId: 'G-9WEDZWFQQX',
  );
}
